### ISSUE TITLE
Many error when try install Archlinux

### ISSUE THREAD

**Issue by henkidefix** [justinethier/cyclone#559]
Tryd to compile on Archlinux with gcc 15.1.1

I got so many errors, don't know where to start, but they seem very similar:

Error: too many arguments to function ‘(void * (*)(void))((closure0_type *)__glo_make_91record_91marker_191_191inline_191_191_scheme_base)->fn’; expected 0, have 2

a lot of errors like: if( (boolean_f != ((inline_function_type)

All related to lambda functions 
like __lambda_1294 , __lambda_1198 and so on and so on until __lambda_31

Note:  i installed cyclone a few months ago , it worked nice. Recently noticed most of my little scripts fail due to gcc compile errors. Than decide to try a fresh compile.
Maybe the guys at gcc one again made some incompatible changes?

Regards,
Henk
(keep up the good work :-)

**Comment by henkidefix** [comment]
Just tested: downgrade to gcc 14: build cyclone with only 1 warning. 
Now most of my small test scripts work again as expected.

**Comment by justinethier** [comment]
Thanks for the bug report and follow-up! Let me see about getting a setup going with GCC 15, definitely would seem there is a problem there based on your findings.

**Comment by mbillingr** [comment]
Hi there!

From this discussion it seems to me, Cyclone is not (yet) compatible with GCC 15.
While this does not work it might be useful to un-break the Archlinux installation by explicitly depending on GCC 14.
This allowed me to install Cyclone, run the REPL and compile a simple Scheme program.

Unfortunately, I don't know how to contribute to AUR packages, so I'm using this channel. Here is a patch for PKGBUILD:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 46b6149..9bc4c5b 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -7,7 +7,7 @@ arch=('i686' 'x86_64')
 url="https://github.com/justinethier/cyclone-bootstrap"
 license=('MIT')
 groups=()
-depends=('libck' 'gcc' 'make')
+depends=('libck' 'gcc14' 'make')
 makedepends=()
 optdepends=()
 provides=()
@@ -23,6 +23,7 @@ noextract=()
 md5sums=('4e8231cfb57393cd32c971da6073464a')

 build() {
+  export CC=/usr/bin/gcc-14
   cd "cyclone-bootstrap-$pkgver"
   make libcyclone.a PREFIX=/usr CFLAGS="-O2 -fPIC -rdynamic -Wall -Iinclude -L." LDFLAGS="-L. -Wl,--export-dynamic"
   make cyclone PREFIX=/usr CFLAGS="-O2 -fPIC -rdynamic -Wall -Iinclude -L." LDFLAGS="-L. -Wl,--export-dynamic"
```

**Comment by ncopa** [comment]
I'm bumping into this as well on alpine linux. We don't have gcc14 fallback. How can we add `-std=gnu17` as default c-compiler option?

**Comment by shriramters** [comment]
For people still facing this issue, you can build cyclone-bootstrap with GCC 15+ by adding `-std=gnu17` to the Makefile.config

change these lines:

```
# Compiler options
CFLAGS       += $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument -Iinclude
BASE_CFLAGS  ?= $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument
# Used by Cyclone to compile programs, no need for PIC there
BASE_PROG_CFLAGS   ?= $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -Wall
```


to this:

```
# Compiler options
CFLAGS       += $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -std=gnu17 -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument -Iinclude
BASE_CFLAGS  ?= $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -std=gnu17 -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument
# Used by Cyclone to compile programs, no need for PIC there
BASE_PROG_CFLAGS   ?= $(CYC_PROFILING) $(CYC_GCC_OPT_FLAGS) -std=gnu17 -Wall
```
